# This is a basic workflow to help you get started with Actions

name: Build C++ Program

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "branchMake" branch
  push:
    branches: [ "branchMake" ]
  # Allows you to run this workflow manually from the Actions tab
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build project
        run: make

      - name: Generate tarball
        run: |
          autoreconf --install
          ./configure
          make dist
