name: Build C++ Program
on:
  push:
    branches:
      - branchMake
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      uses: actions/checkout@v3
      - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build project
      run: make
      - name: Generate tarball
      run: |
        autoreconf --install
        ./configure
        make dist
      - name: Build Debian package
      run: dpkg-buildpackage -us -uc -b
      - name: Run test
      run: make check
